######
# Configuracion Kubernetes Config
######

spring:
  config:
    import: "kubernetes:"
  cloud:
    kubernetes:
      config:
        enabled: true
        sources:
          - name: @project.artifactId@
          - name: bbdd
          - name: osb
          - name: rest
          - name: context-shared
